@startuml

left to right direction

actor Pilote

rectangle "Hôte A" {

    rectangle "Stack ArduSub" <<Subsystem>> {

        rectangle QGroundControl
        rectangle MAVProxy

        usecase (communique) as comm1

        Pilote -- (gérer flight path)
        Pilote -- (pilotage manuel)
        Pilote -- (recevoir flux vidéo)
        (gérer flight path) -- QGroundControl
        (pilotage manuel) -- QGroundControl
        (recevoir flux vidéo) -- QGroundControl

        QGroundControl -- comm1
        comm1 -- MAVProxy

    }

}

rectangle "Hôte B" {

    rectangle ArduSub

    usecase (communique) as comm2

    MAVProxy -down- comm2
    comm2 -down- ArduSub

    rectangle Simulateur <<Subsystem>> {
        ArduSub -down- (contrôler les moteurs)
        ArduSub -down- (lire les capteurs)
    }
}

@enduml
