@startuml

left to right direction



rectangle "Machine Client" {
    component Launcher
    component QGroundControl
    component ArduSub
    component "Jme Renderer" as JmeRenderer
    component "MAVSec proxy" as SecProxy1



    note right of Launcher
        Permet de démarrer les différents composants du client.
    end note
    QGroundControl -- ArduSub : MAVLink
    ArduSub -- SecProxy1 : MAVLink
    QGroundControl -down- JmeRenderer : H.264 video
    note right of JmeRenderer
        C'est le launcher qui lance Jme Renderer.
    end note
}




rectangle "Machine Serveur" {
    component "Jme Server" as JmeServer
    component "MAVSec proxy" as SecProxy2
    component "Controleur" as Controller
    component "Manager" as Manager

    note left of Manager
        API REST
        Permet de démarrer les différents composants du serveur et de gérer
        l'authentification.
    end note

    JmeRenderer - JmeServer : UDP Custom Chiffré
    Controller -- JmeServer
    Controller -- SecProxy2
    SecProxy1 -- SecProxy2 : MAVSec
    Launcher -- Manager
    Manager -- JmeServer : Intéragit
}


@enduml
