@startuml

left to right direction

actor Pilote
actor Operator
actor Admin

rectangle "Machine Client" {
    component Launcher
    component "Video Decoder" as VideoDecoder
    component QGroundControl
    component MAVProxy
    component ArduSub
    component "MAVSec proxy" as SecProxy1

    Pilote -- QGroundControl : IHM
    Pilote -- Launcher : Lancer le client
    note right of Launcher
        Permet de démarrer les différents composants du client.
    end note
    QGroundControl -left- MAVProxy : MAVLink
    MAVProxy -- ArduSub : MAVLink
    ArduSub -- SecProxy1 : MAVLink
}

component "Operator Client" as OperatorClient
component "Admin Client" as AdminClient

rectangle "Machine Serveur" {
    component "MAVSec proxy" as SecProxy2
    component "Video Decoder" as JmeRenderer
    component "Jme Renderer" as JmeRenderer
    component "Jme Server" as JmeServer

    SecProxy2 -left- JmeRenderer : MAVLink
    JmeRenderer -- JmeServer : UDP Custom
    OperatorClient -- JmeServer : Control
    AdminClient -- JmeServer : Configuration
}

SecProxy1 -- SecProxy2 : MAVSec
QGroundControl -- VideoDecoder : H.264 clair
VideoDecoder -- JmeRenderer : H.264 chiffré
Operator -- OperatorClient
Admin -- AdminClient

@enduml
