@startuml

left to right direction

actor Pilote

rectangle "Hôte A" {
    rectangle "Stack ArduSub" <<Subsystem>> {

        rectangle QGroundControl
        rectangle MAVProxy
        rectangle ArduSub

        usecase (communique) as comm1
        usecase (communique) as comm2

        Pilote -- (gérer flight path)
        Pilote -- (piloter manuellement)
        Pilote -- (recevoir flux vidéo)
        (gérer flight path) -- QGroundControl
        (pilotage manuel) -- QGroundControl
        (recevoir flux vidéo) -- QGroundControl

        QGroundControl -- comm1
        comm1 -- MAVProxy

        MAVProxy -- comm2
        comm2 -- ArduSub

    }
}

rectangle "Hôte B" {
    rectangle Simulateur <<Subsystem>> {
        ArduSub -down- (contrôler les moteurs)
        ArduSub -down- (lire les capteurs)
    }
}

@enduml
