@startuml

left to right direction


rectangle "Machine Client" {
    component "Launcher" as Launcher
    component "Video Decoder" as VideoDecoder
    component QGroundControl
    component "MAVSec proxy" as SecProxy1
    component ArduPilot

    note right of Launcher
        Permet de démarrer les différents composants du client.
    end note
    QGroundControl -- ArduPilot : MAVLink
    ArduPilot -- SecProxy1 : MAVLink
}


rectangle "Machine Serveur" {
    component "Controleur" as Controller
    component "Video Decoder" as JmeRenderer
    component "Jme Renderer" as JmeRenderer
    component "Jme Server" as JmeServer
    component "MAVSec proxy" as SecProxy2
    component "Manager" as Manager

    Controller -- JmeServer
    JmeRenderer -- JmeServer : UDP Custom
    Manager -- JmeServer : Intéragit
    Manager -- JmeRenderer : Démarre
    Launcher -- Manager : REST
    Controller -- SecProxy2


    note left of Manager
        API REST
        Permet de démarrer les différents composants du serveur et de gérer
        l'authentification.
    end note
}

SecProxy1 -- SecProxy2 : MAVSec
QGroundControl -- VideoDecoder : H.264 clair
VideoDecoder -- JmeRenderer : H.264 chiffré


@enduml
