@startuml

package simulation {
    class Modele {
        +name: String
        +type: String
        +weight: float
        +dimensions: String
    }

    class Drone {
        +id: String
        +model: Model
        +batteryLevel: int
        +location: String
        +videoStream: VideoStream
        +sensors: List<Sensor>
        +pilotDrone(): void
    }



    class Évènement {
        +type: String
        +location: String
        +description: String
    }

    class Simulateur {
        +map: String
        +weatherConditions: String
        +startSimulation(): void
        +stopSimulation(): void
        +changeMap(): void
        +manageSimulation(): void
        +configureDrone(): void
    }
}

package réseau {
    class ControleurRéseau {
        receiveData(): void
        sendData(): void
    }

    abstract ControleurDrone {
        +getMotorSpeed(index: int): float
        +getSensorReading(Sensor sensor): void
        +setMotorSpeed(index: int, value: float): void
    }

    class ArduSubRemoteControler {
    }

}

package testing{
    class LocalTestingControler {
    }

}


package utilisateurs {
    class Pilote {
        +Drone drone
    }

    class MDJ {

    }

    class Observateur {
        +viewEnvironment(): void
        +followDrone(drone: Drone): void
        +consultDroneInfo(drone: Drone): void
    }

    class Admin {
        +createUser(user: Utilisateur): void
        +deleteUser(user: Utilisateur): void
        +excludeUser(user: Utilisateur): void
    }

    class Utilisateur {
        +username: String
        +password: String
        +ValidKeys: List<String>
}
}


' Define relationships
Observateur <|-- MDJ
Utilisateur <|-- Pilote
Utilisateur <|-- Observateur
Utilisateur <|-- Admin

Simulateur "1" -- "1..n" Drone : gère
Simulateur "1" -- "1" MDJ : gère
Simulateur "1" -- "0..n" Observateur : observe
Simulateur "1" -- "1..n" Pilote : gère
Simulateur "1" -- "1" ControleurRéseau : communique
Simulateur "1" -- "1" Admin : gère
Simulateur "1" -- "0..n" Évènement : gère

Pilote "1" -- "1" ControleurDrone : pilote
Drone "1..n" -- "1" Modele : est un type
Drone "1" -- "1" ControleurDrone : Possède

LocalTestingControler --|> ControleurDrone
ArduSubRemoteControler --|> ControleurDrone
@enduml
