@startuml

package simulation {
    class Modele {
        +name: String
        +type: String
        +weight: float
        +dimensions: String
        +mesh: Mesh3D
        +motors: MotorDescription[]
        +sensors: SensorDescription[]
    }

    class Drone {
        +id: String
        +batteryLevel: int
        +location: Vec3
    }



    abstract class Évènement {
        +{static}shortDescription: String
        +{static}longDescription: String
        +location: String
        +trigger()
        +schedule(time)
        +cancel()
    }

    class Simulateur {
        +map: String
        +weatherConditions: String
        +startSimulation(): void
        +stopSimulation(): void
        +changeMap(): void
        +manageSimulation(): void
        +configureDrone(): void
    }


    interface ControleurDrone {
        +getMotorSpeed(index: int): float
        +setSensorReading(index: int): void
    }
}

package réseau {
    class ArduSubRemoteControler implements simulation.ControleurDrone {
    }
}

package testing{
    class LocalTestingControler implements simulation.ControleurDrone {
    }
}


package utilisateurs {
    class Pilote extends Utilisateur {
        +Drone drone
    }

    class MDJ extends Utilisateur {

    }

    class Observateur extends Utilisateur {
        +viewEnvironment(): void
        +followDrone(drone: Drone): void
        +consultDroneInfo(drone: Drone): void
    }

    class Admin extends Utilisateur {
        +createUser(user: Utilisateur): void
        +deleteUser(user: Utilisateur): void
        +excludeUser(user: Utilisateur): void
    }

    abstract class Utilisateur {
        +username: String
        +password: String
        +ValidKeys: List<String>
    }
}

MDJ "1" -down- "0..n" Évènement : crée/annule
Observateur "0..n" -down- "1" Simulateur : observe
Pilote "1" -- "1" ArduSubRemoteControler : pilote
Admin -- Utilisateur : crée/supprime

Simulateur "1" -- "0..n" Évènement : réagit
Simulateur "1" -- "1..n" Drone : gère

Drone "1..n" -- "1" Modele : est un type
Drone "1" -- "1" simulation.ControleurDrone : Possède

@enduml
