@startuml

!pragma teoz true

skinparam BoxPadding 10

box "Machine Client"
    participant Pilote
    participant Lanceur
    participant "MAVSec Proxy" as ProxyClient
    participant "Proxy chiffrement\nde vidéo" as Décodeur
end box

box "Machine Serveur"
    participant "Serveur\nd'Authentification" as Auth
    participant Renderer
    participant Simulateur
end box

Pilote -> Lanceur : Renseigne identifiants
Lanceur -> Auth : Authentification
Auth -> Lanceur : OK
Auth -> Lanceur : Liste de drones avec flux vidéo et clés associé
Lanceur -> Pilote : Menu de sélection de drone
Pilote -> Lanceur : Sélectionne un drone

Lanceur -> ProxyClient ** : Configure connexion et clé de chiffrement
Lanceur -> Décodeur ** : Configure connexion et clé de chiffrement
Lanceur ->? : Lance les autres composantes...

ProxyClient -> Simulateur : Se connecte
Décodeur -> Renderer : Se connecte

?<-> ProxyClient : échange des messages MAVLink
& ProxyClient <-> Simulateur : Forward les messages MAVLink
Décodeur <- Renderer : Envoie vidéo
& ?<- Décodeur : Forward la vidéo à l'interface de pilotage

@enduml
