@startuml

!pragma teoz true

skinparam BoxPadding 10

actor Pilote

box "Machine Client"
    participant Launcher
    participant "QGC" as QGC
    participant "Ardupilot" as ArduPilot
end box

box "Machine Serveur"
    participant "Manager" as Manager
    participant "Renderer" as RendererRemote
    participant Simulateur
end box

Pilote -> Launcher : Renseigne identifiants
Launcher -> Manager : Demande Authentification
Manager -> Launcher : Authentification OK
Launcher -> Pilote : Affiche interface pilote
Pilote -> Launcher : Clique sur "Lancer la simulation"
Launcher -> Manager : Demande connexion au simulateur
Manager -> Simulateur : Prépare la Connexion du pilote
Simulateur -> Manager : Connexion prête
Manager -> RendererRemote : Démarre
RendererRemote -> Simulateur : Se connecte
Simulateur -> RendererRemote : Connexion établie
RendererRemote -> Manager : Démarrage terminé
Manager -> Launcher : Simulation prête à accueillir le pilote

par
Launcher -> QGC : Démarre
QGC -> ArduPilot : Se connecte
ArduPilot -> QGC : Connexion établie
RendererRemote -> QGC : Envoie le flux vidéo
QGC -> Pilote : Affiche la vidéo
else
Launcher -> ArduPilot : Démarre
ArduPilot <- Simulateur : Se connecte
Simulateur <- ArduPilot : Connexion établie








@enduml
