@startuml

left to right direction

actor Observateur
actor MDJ
actor Pilote
actor Admin
'actor Admin

rectangle "Système de Pilotage" <<Subsystem>> as SysPilot {
    Pilote -- (gérer flight path)
    Pilote -- (piloter manuelement)
    Pilote -- (recevoir flux vidéo)
}



MDJ -left-|> Observateur

rectangle Simulateur <<Subsystem>> {

    usecase (suivre un drone) as follow_drone

    follow_drone <.down. (changer le mode\npremière/troisième personne) : extends

    Observateur -- (se deplacer librement)
    Observateur -- (voir drones et carte)
    Observateur -- follow_drone

    usecase (configurer un drone) as cfg_drone
    usecase (configurer connectivité) as cfg_conn
    usecase (configurer crypto) as cfg_crypt
    usecase (configurer ArduPilot coté serveur) as cfg_ardu_ss
    usecase (configurer micro logiciel coté client) as cfg_ardu_cs
    note "configurations incompatibles" as mutex1

    cfg_drone .down.> cfg_conn : includes
    cfg_conn <.down. cfg_crypt : extends
    cfg_drone <|-- cfg_ardu_ss 
    cfg_drone <|-- cfg_ardu_cs 
    cfg_ardu_ss .. mutex1
    cfg_ardu_cs .. mutex1

    MDJ -- (changer la carte)
    MDJ -- (gérer les condition météo)
    MDJ -- cfg_drone

    Admin -- (gérer les utilisateurs)

}

@enduml
