@startuml

left to right direction

actor Observateur
actor MDJ
actor Pilote
actor Admin
'actor Admin

rectangle "Système de Pilotage" <<Subsystem>> as SysPilot {
    Pilote -- (Piloter manuelement)
    Pilote -- (Recevoir flux vidéo)
    Pilote -- (Consulter les capteurs)

    (Recevoir flux vidéo) ..> (Rejoindre une simulation) : includes
    (Piloter manuelement) ..> (Rejoindre une simulation) : includes
    (Consulter les capteurs) ..> (Rejoindre une simulation) : includes
}

MDJ -left-|> Observateur

rectangle Simulateur <<Subsystem>> {

    usecase (Suivre un drone) as follow_drone

    follow_drone <.down. (Changer le mode\npremière/troisième personne) : includes
    (Voir environement) <.. (Se deplacer librement) : includes

    Observateur -- (Voir environement)
    Observateur -- follow_drone
    Observateur -- (Consulter infos drones)

    usecase (Configurer un drone) as cfg_drone
    usecase (Configurer connectivité) as cfg_conn
    usecase (Configurer crypto) as cfg_crypt
    usecase (Configurer client en mode "lourd") as cfg_ardu_ss
    usecase (Configurer client en mode "cloud") as cfg_ardu_cs
    usecase (Attitrer un drone) as cfg_attrib_drone
    usecase (Lancer une simulation) as cfg_sim
    note "configurations incompatibles" as mutex1
    note "Les cartes et leurs assets d'événements sont créés en amont par les développeurs." as note1

    cfg_drone .down.> cfg_conn : includes
    cfg_conn <.down. cfg_crypt : extends
    cfg_drone <|-- cfg_ardu_ss
    cfg_drone <|-- cfg_ardu_cs
    cfg_ardu_ss .. mutex1
    cfg_ardu_cs .. mutex1
    cfg_drone <|--  cfg_attrib_drone

    MDJ -- (Changer la carte)
    (Changer la carte) .. note1
    MDJ -- (Gerer Simulation)
    (Gerer Simulation) <|-- (Gérer les condition météo)
    (Gerer Simulation) <|-- (Gérer les évènements)
    MDJ -- cfg_drone
    MDJ -- cfg_sim

    Admin -- (Gérer les utilisateurs)
    (Gérer les utilisateurs) <|-- (Créer utilisateur)
    (Gérer les utilisateurs) <|-- (Supprimer utilisateur)
    (Gérer les utilisateurs) <|-- (Exclure utilisateur)

}

@enduml
